export const SET_LOCATION = 'app/App/SET_LOCATION';
export const START_LOCATION = 'app/App/START_LOCATION';
export const DESTINATION = 'app/App/DESTINATION';

export const FETCH_DIRECTIONS_REQUEST = 'app/App/FETCH_DIRECTIONS_REQUEST';
export const FETCH_DIRECTIONS_SUCCESS = 'app/App/FETCH_DIRECTIONS_SUCCESS';
export const FETCH_DIRECTIONS_ERROR = 'app/App/FETCH_DIRECTIONS_ERROR';
export const TOGGLE_DIRECTIONS_LOADING = 'app/App/TOGGLE_DIRECTIONS_LOADING';
